### ISSUE TITLE
Provide ability to specify parameters and their metadata for query, map*, and generic adapters

### ISSUE THREAD

**Issue by mwvaughn** [Arabidopsis-Information-Portal/adama#35]
As part of our attempt to create automatically documenting APIs and do input validation, I propose to extend the metadata scheme for ADAMA to allow publishers to specify parameters and metadata, much like we do for Agave /apps parameters. Ideally, we'd use near-identical metadata schemes to promote compatibility with Agave core APIs.

**Comment by waltermoreira** [comment]
We decided to support Swagger version 2.0, which is easier and more clear to write.

**Comment by waltermoreira** [comment]
Deployed in Adama v0.3. Will be advertised in Adama v0.4.
