### ISSUE TITLE
ADAMA should return provenance information in its responses. 

### ISSUE THREAD

**Issue by mwvaughn** [Arabidopsis-Information-Portal/adama#41]
There's quite a bit of design work in this one before we decide on an implementation:

ADAMA should be able to send back developer-specified provenance/attribution with its responses. In our service types that return JSON, this may need to be an extra entry in the response document. In services where we don't control the response content, we may consider injecting a custom Header into our response.

**Comment by waltermoreira** [comment]
All adapters return provenance now.
