### ISSUE TITLE
Setup a regular job for backing up

### ISSUE THREAD

**Issue by waltermoreira** [Arabidopsis-Information-Portal/adama#43]
Need to define where to upload backups for storage, and frequency of backups.

**Comment by waltermoreira** [comment]
Backup job is running once a day, saving the data locally.  VM's are being backed up at TACC, but is there any other good place to save the tarballs?

**Comment by stevemock** [comment]
Ranch.

--Steve

On Jun 25, 2015, at 9:15 PM, Walter Moreira <notifications@github.com<mailto:notifications@github.com>> wrote:


Backup job is running once a day, saving the data locally. VM's are being backed up at TACC, but is there any other good place to save the tarballs?

-

**Comment by waltermoreira** [comment]
Thanks, Ranch it is, then.  Closing this issue now.
