### ISSUE TITLE
Provide usage endpoint

### ISSUE THREAD

**Issue by mwvaughn** [Arabidopsis-Information-Portal/adama#53]
Each ADAMA service should feature a /usage endpoint that can report at minimum the number of times it has been accessed. We can iterate on refinements in future versions.

**Comment by waltermoreira** [comment]
Good point.  Should we call it "statistics" or "stats" instead?  "Usage" makes me think of instructions about how to use it, and it's not as general if we want to include other metrics later.

On Mar 24, 2015, at 10:51 AM, Matthew Vaughn <notifications@github.com<mailto:notifications@github.com>> wrote:


Each ADAMA service should feature a /usage endpoint that can report at minimum the number of times it has been accessed. We can iterate on refinements in future versions.

**Comment by mwvaughn** [comment]
Sure thing. I just want to get the base ability in place as its a deliverable in the original project plan.

**Comment by mwvaughn** [comment]
What would be interesting, longer term, is to get all the services sending log messages to something like LogStash. Then, we could do deep-dive analytics on platform usage.

**Comment by stevemock** [comment]
FYI anything logged to syslog on TACC VMWare VMs will automatically get pushed into our central splunk server.

**Comment by waltermoreira** [comment]
A simple /stats endpoint for each service is now provided.  Right now stats are saved to the Redis database. We may want to revamp it in the future.
