### ISSUE TITLE
ADAMA should allow developers to specify JSON schema to which responses conform

### ISSUE THREAD

**Issue by mwvaughn** [Arabidopsis-Information-Portal/adama#54]
Related to [https://github.com/Arabidopsis-Information-Portal/adama/issues/24]: For the prototype release, ADAMA should allow developers to specify either a list of URI or files local to the source repo that define JSON schemas that the service intends to respond with. This lays groundwork for validation in the future.

**Comment by waltermoreira** [comment]
This wasn't closed before, but it's supported since we have full swagger 2.0 support for models in the responses.  Users can build the `endpoints:` field with the model for the responses.  Swagger support external references with `$ref`.
