### ISSUE TITLE
Should not return 200 when adapters raise exceptions

### ISSUE THREAD

**Issue by waltermoreira** [Arabidopsis-Information-Portal/adama#69]
Return error message together with proper error code (4xx or 5xx).

**Comment by waltermoreira** [comment]
There is one important detail with respect to `query` adapters (feedback is most welcome):

Query adapters return an **stream**. They don't wait until getting all the data from the third party services (that's the reason of the `prints` rather than a `return`).  To do this, we return a 200 status code, and proceed to stream the standard output of the adapter.  If an adapter raises an exception, then it's already too late to change the status code.

There are at least two possible solutions:

- Remove the streaming feature (-1 from me, since it will be really useful for responsive front ends when data sources are big).
- Fetch the first record from the adapter's response.  It that produces an exception, then return 4xx/5xx, otherwise return 200 and proceed to stream.  Most exceptions are because of connection errors, bad responses from the third party service, missing packages, and things that happen before the first `print`. This solution will work as expected in those cases.  It would only fail unexpectedly (status 200 but an error) if an adapter raises an exception in the middle of the streaming. It could still arguably be considered a "success", since it delivered data (at least one record).

Any other proposals?

**Comment by mwvaughn** [comment]
The second option is quite reasonable.

**Comment by eriksf** [comment]
I like the second option.

**Comment by waltermoreira** [comment]
Thanks for the feedback, folks.  The second option is now complete in commit f39cde7575769d5ebcaf68188fa77738abfa051f
