### ISSUE TITLE
Add ability to specify timeout on a per-service basis

### ISSUE THREAD

**Issue by mwvaughn** [Arabidopsis-Information-Portal/adama#75]
For some remote services being served via ADAMA, the default timeout of 30s is too short. I would recommend we allow service creators to specify a longer timeout, with 30s being the default. A perfect example is aip/atted_coexpressed_by_locus_v0.2.0

**Comment by waltermoreira** [comment]
Fixed in commit 32273261851970e5df0b51a0795cea2743389b2d

Not that `aip/atted_coexpressed_by_locus_v0.2.0` was timing out because of a missing ip in whitelist.
