### ISSUE TITLE
Exception in user API causes timeout for subsequent API calls

### ISSUE THREAD

**Issue by timeu** [Arabidopsis-Information-Portal/adama#94]
I am not sure if this is by design or a bug: 

I created a simple community API (code is [here](https://github.com/Gregor-Mendel-Institute/araport-athaliana-master-accession-table)) that queries a Google fusion table and returns the data. 

The service works fine, however if the service throws an Exception by calling `raise Exception('some error message')`  alll subsequent API calls seem to timeout with following error payload:

```json
{
  "exception": "TimeoutException",
  "message": "result channel tcp://172.17.42.1:41316 has been idle for more than 30 seconds",
  "status": "error",
  "worker_trace": null
}
```

The only way to fix this is to delete the service and re-create it and avoid throwing an ` Exception`. 

Are there any guidelines how to deal with error when calling a third party service ? (I couldn't find anything in the docs). Should we throw or just return an error payload ?

**Comment by timeu** [comment]
Just an update. I also get the same `TimeoutException` even without raising an `Exception` after a while.

**Comment by waltermoreira** [comment]
Looking at the code, I see that the full result of the external request is printed at the same time.  The proper way is to iterate of the result and print the objects with `json.dumps` and with `---` interspersed.

Please, fix https://github.com/Gregor-Mendel-Institute/araport-athaliana-master-accession-table/blob/master/services/query/main.py#L18-L20 and report back is the timeout is still happenning.

**Comment by vivekkrish** [comment]
@timeu , I think the distinction is that in an ADAMA adapter of type 'query' (which is what you have chosen currently), the results have been to be iterated through and atomically printed to `sys.stdout` with `---` separators. This allows ADAMA to stream the data to the entity that made the request.

However, if you wish to not iterate over your results, you should switch your adapter type to 'generic', in which case, you can just ```return 'application/json', json.dumps(ret.json())```, without the need to print.

Thank you!
Vivek

**Comment by timeu** [comment]
@vivekkrish , @waltermoreira: Thanks for the info. I switched to the ADAMA adapter to type `generic`  and sof ar it seems to work. I will close the issue for now.

**Comment by timeu** [comment]
I think I still run into the issue. I switched to a `generic`  adapter type and first it worked fine but after a couple of successful requests, a `TimeoutException` is thrown and I need to delete the service and re-create it. 
I tried to run it locally to see if the request to the fusion table times out but I couldn't get it to timeout (I am also way below the quota limit of the fusion table). 
Is there any way to debug this issue ?

**Comment by vivekkrish** [comment]
@timeu , are you experiencing the timeouts on the API explorer at araport.org or while making requests to your adapter from the command line via curl?

**Comment by timeu** [comment]
@vivekkrish In both: 
I tried it with Postman (REST GUI App) but also from the API explorer site. I also made sure that there are worker free by checking the health endpoint.

**Comment by vivekkrish** [comment]
@timeu Could you please the full request URL with the exact (logical) set of parameters you used? The API explorer UI shows many query params but there are no defaults (I did find some example values in the query param "Description").

Also, if one does not provide a value for the LIMIT param, what is the potential size of the output generated by such a query?

**Comment by timeu** [comment]
@vivekkrish 
curl  -H "Authorization: Bearer $TOKEN"  "https://api.araport.org/community/v0.3/gmi/master_accession_list_v0.1.0/list?country=SWE&LIMIT=10"
(this should retrieve 10 rows)

By default it will retreive 7425 rows.

**Comment by waltermoreira** [comment]
It seems that google changes frequently the ip associated to
www.googleapis.com, so the ip enabled in the firewall of the adapter inside
adama is not the proper one after a while.  That's why it's working for
sometime after registration (the domain name is resolved at registration
time).   There will need to be a crontab in adama running and updating such
firewalls from the domain names.  I'll open a separate ticket.

**Comment by timeu** [comment]
@waltermoreira: That makes sense. 
Great thanks !

**Comment by vivekkrish** [comment]
@waltermoreira , could your container iptables be set to allow the entire IP range based on the CIDR block: 173.194.0.0/16 (for googleapis.com)?

**Comment by waltermoreira** [comment]
Hmm, @vivekkrish where are you getting that block from?  The ip's for www.googleapis.com (the ones accessed by Ümit) seem to be in the range 216.58.218.0.

**Comment by waltermoreira** [comment]
Allowing a range of ip's is a possible solution, though.  Maybe a bit more permissive than what I would like, and still not a complete solution (such as in cases where a service is migrated from one network to another).  Open to comments anyway...

**Comment by vivekkrish** [comment]
@waltermoreira, I found it on this page: https://myip.ms/info/whois/173.194.112.144/k/295008155/website/googleapis.com. 

However, the CIDR block is labeled as Hosting CDR, so it is a bit confusing to me.

**Comment by waltermoreira** [comment]
After conversation with Vivek, we solved this case by disabling the firewall in this particular adapter.  It wasn't clear what ranges of ip's to allow for googleapis, and refreshing the ip from the domain name was still leaving windows of time where things would fail.

There is now a flag, that only admins can toggle, to disable firewalls in selected adapters.  Not sure is a permanent solution, but we need it for now.

**Comment by timeu** [comment]
@waltermoreira: Thanks I will try it out.
